#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarsztatAplikacja
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Warsztat")]
	public partial class linqtosqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertczesci(czesci instance);
    partial void Updateczesci(czesci instance);
    partial void Deleteczesci(czesci instance);
    partial void Insertklienci(klienci instance);
    partial void Updateklienci(klienci instance);
    partial void Deleteklienci(klienci instance);
    #endregion
		
		public linqtosqlDataContext() : 
				base(global::WarsztatAplikacja.Properties.Settings.Default.WarsztatConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UzytkownicyAplikacji> UzytkownicyAplikacji
		{
			get
			{
				return this.GetTable<UzytkownicyAplikacji>();
			}
		}
		
		public System.Data.Linq.Table<czesci> czesci
		{
			get
			{
				return this.GetTable<czesci>();
			}
		}
		
		public System.Data.Linq.Table<klienci> klienci
		{
			get
			{
				return this.GetTable<klienci>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectLogin")]
		public ISingleResult<SelectLoginResult> SelectLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Login", DbType="NVarChar(50)")] string par_Login)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Login);
			return ((ISingleResult<SelectLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectLogin2")]
		public ISingleResult<SelectLogin2Result> SelectLogin2()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectLogin2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.czesci_wybór")]
		public ISingleResult<czesci_wybórResult> czesci_wybór([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_czesci", DbType="Int")] System.Nullable<int> par_id_czesci, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa_czesci", DbType="VarChar(50)")] string par_Nazwa_czesci, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr_czesci", DbType="VarChar(15)")] string par_Nr_czesci, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_dostawcy", DbType="Int")] System.Nullable<int> par_id_dostawcy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Data_dostawy", DbType="Date")] System.Nullable<System.DateTime> par_Data_dostawy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Ilosc_w_magazynie", DbType="NChar(10)")] string par_Ilosc_w_magazynie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id_czesci, par_Nazwa_czesci, par_Nr_czesci, par_id_dostawcy, par_Data_dostawy, par_Ilosc_w_magazynie);
			return ((ISingleResult<czesci_wybórResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_czesci")]
		public ISingleResult<select_czesciResult> select_czesci()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_czesciResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_dostawcy")]
		public ISingleResult<select_dostawcyResult> select_dostawcy()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_dostawcyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_naprawy")]
		public ISingleResult<select_naprawyResult> select_naprawy()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_naprawyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_samochody")]
		public ISingleResult<select_samochodyResult> select_samochody()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_samochodyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_klienci_kontakt")]
		public ISingleResult<select_klienci_kontaktResult> select_klienci_kontakt()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_klienci_kontaktResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_dostawcy_kontakt")]
		public ISingleResult<select_dostawcy_kontaktResult> select_dostawcy_kontakt()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_dostawcy_kontaktResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_klienci")]
		public ISingleResult<select_klienciResult> select_klienci()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_klienciResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_dostawcy")]
		public ISingleResult<select_dostawcyResult1> select_dostawcy1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_dostawcyResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_czesci")]
		public ISingleResult<select_czesciResult1> select_czesci1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_czesciResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dostawcy_wstawianie")]
		public int dostawcy_wstawianie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_dostawcy", DbType="Int")] System.Nullable<int> par_id_dostawcy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa", DbType="VarChar(50)")] string par_Nazwa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kraj", DbType="VarChar(50)")] string par_Kraj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id_dostawcy, par_Nazwa, par_Kraj);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dostawcy_usuwanie")]
		public int dostawcy_usuwanie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_dostawcy", DbType="Int")] System.Nullable<int> par_id_dostawcy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa", DbType="VarChar(50)")] string par_Nazwa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kraj", DbType="VarChar(50)")] string par_Kraj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id_dostawcy, par_Nazwa, par_Kraj);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dostawcy_wstawianie")]
		public int dostawcy_wstawianie1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa", DbType="VarChar(50)")] string par_Nazwa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kraj", DbType="VarChar(50)")] string par_Kraj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Nazwa, par_Kraj);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dostawcy_usuwanie")]
		public int dostawcy_usuwanie1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_dostawcy", DbType="Int")] System.Nullable<int> par_id_dostawcy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id_dostawcy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dostawcy_aktualizacja")]
		public int dostawcy_aktualizacja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_dostawcy", DbType="Int")] System.Nullable<int> par_id_dostawcy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa", DbType="VarChar(50)")] string par_Nazwa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kraj", DbType="VarChar(50)")] string par_Kraj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id_dostawcy, par_Nazwa, par_Kraj);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_select_id_where_miasto")]
		public ISingleResult<klienci_select_id_where_miastoResult> klienci_select_id_where_miasto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Imie", DbType="VarChar(50)")] string par_Imie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Imie);
			return ((ISingleResult<klienci_select_id_where_miastoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_kontakt_wstawianie")]
		public int klienci_kontakt_wstawianie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Misto", DbType="Char(50)")] string par_Misto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kod_pocztowy", DbType="Char(50)")] string par_Kod_pocztowy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Ulica", DbType="Char(50)")] string par_Ulica, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr", DbType="Char(50)")] string par_Nr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_telefon", DbType="Char(50)")] string par_Kontakt_telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_email", DbType="Char(50)")] string par_Kontakt_email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Misto, par_Kod_pocztowy, par_Ulica, par_Nr, par_Kontakt_telefon, par_Kontakt_email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_wstawianie")]
		public int klienci_wstawianie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Imie", DbType="VarChar(50)")] string par_Imie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwisko", DbType="VarChar(50)")] string par_Nazwisko, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Data_pierwszej_wizyty", DbType="Date")] System.Nullable<System.DateTime> par_Data_pierwszej_wizyty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nazwa_firmy", DbType="Char(50)")] string par_Nazwa_firmy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nip", DbType="NChar(10)")] string par_Nip)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Imie, par_Nazwisko, par_Data_pierwszej_wizyty, par_Nazwa_firmy, par_Nip);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_kontakt_wstawianie")]
		public int klienci_kontakt_wstawianie1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Misto", DbType="Char(50)")] string par_Misto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kod_pocztowy", DbType="Char(50)")] string par_Kod_pocztowy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Ulica", DbType="Char(50)")] string par_Ulica, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr", DbType="Char(50)")] string par_Nr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_telefon", DbType="Char(50)")] string par_Kontakt_telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_email", DbType="Char(50)")] string par_Kontakt_email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_klient", DbType="Int")] System.Nullable<int> par_id_klient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Misto, par_Kod_pocztowy, par_Ulica, par_Nr, par_Kontakt_telefon, par_Kontakt_email, par_id_klient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_kontakt_wstawianie")]
		public int klienci_kontakt_wstawianie2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Misto", DbType="Char(50)")] string par_Misto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kod_pocztowy", DbType="Char(50)")] string par_Kod_pocztowy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Ulica", DbType="Char(50)")] string par_Ulica, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr", DbType="Char(50)")] string par_Nr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_telefon", DbType="Char(50)")] string par_Kontakt_telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_email", DbType="Char(50)")] string par_Kontakt_email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_klient", DbType="Int")] System.Nullable<int> par_id_klient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Misto, par_Kod_pocztowy, par_Ulica, par_Nr, par_Kontakt_telefon, par_Kontakt_email, par_id_klient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_kontakt_wstawianie")]
		public int klienci_kontakt_wstawianie3([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Misto", DbType="Char(50)")] string par_Misto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kod_pocztowy", DbType="Char(50)")] string par_Kod_pocztowy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Ulica", DbType="Char(50)")] string par_Ulica, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr", DbType="Char(50)")] string par_Nr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_telefon", DbType="Char(50)")] string par_Kontakt_telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Kontakt_email", DbType="Char(50)")] string par_Kontakt_email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_klient", DbType="Int")] System.Nullable<int> par_id_klient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Misto, par_Kod_pocztowy, par_Ulica, par_Nr, par_Kontakt_telefon, par_Kontakt_email, par_id_klient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.klienci_select_id_where_miasto2")]
		public ISingleResult<klienci_select_id_where_miasto2Result> klienci_select_id_where_miasto2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Imie", DbType="VarChar(50)")] string par_Imie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Imie);
			return ((ISingleResult<klienci_select_id_where_miasto2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.widok_wstawianie_rezultat")]
		public ISingleResult<widok_wstawianie_rezultatResult> widok_wstawianie_rezultat()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<widok_wstawianie_rezultatResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.naprawy_raport_wstawianie")]
		public int naprawy_raport_wstawianie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr_raportu", DbType="Char(10)")] string par_Nr_raportu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Opis", DbType="NChar(100)")] string par_Opis)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Nr_raportu, par_Opis);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.widok_wstawianie_rezultat")]
		public ISingleResult<widok_wstawianie_rezultatResult1> widok_wstawianie_rezultat1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id", DbType="Int")] System.Nullable<int> par_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_id);
			return ((ISingleResult<widok_wstawianie_rezultatResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.naprawy_raport_wstawianie")]
		public int naprawy_raport_wstawianie1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Nr_raportu", DbType="Char(10)")] string par_Nr_raportu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_Opis", DbType="NChar(100)")] string par_Opis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Par_id_klient", DbType="Int")] System.Nullable<int> par_id_klient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), par_Nr_raportu, par_Opis, par_id_klient);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UzytkownicyAplikacji")]
	public partial class UzytkownicyAplikacji
	{
		
		private string _Login;
		
		private string _Password;
		
		public UzytkownicyAplikacji()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this._Login = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.czesci")]
	public partial class czesci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_czesci;
		
		private string _Nazwa_czesci;
		
		private string _Nr_czesci;
		
		private System.Nullable<int> _id_dostawcy;
		
		private System.Nullable<System.DateTime> _Data_dostawy;
		
		private string _Ilosc_w_magazynie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_czesciChanging(int value);
    partial void Onid_czesciChanged();
    partial void OnNazwa_czesciChanging(string value);
    partial void OnNazwa_czesciChanged();
    partial void OnNr_czesciChanging(string value);
    partial void OnNr_czesciChanged();
    partial void Onid_dostawcyChanging(System.Nullable<int> value);
    partial void Onid_dostawcyChanged();
    partial void OnData_dostawyChanging(System.Nullable<System.DateTime> value);
    partial void OnData_dostawyChanged();
    partial void OnIlosc_w_magazynieChanging(string value);
    partial void OnIlosc_w_magazynieChanged();
    #endregion
		
		public czesci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this.Onid_czesciChanging(value);
					this.SendPropertyChanging();
					this._id_czesci = value;
					this.SendPropertyChanged("id_czesci");
					this.Onid_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_czesci", DbType="VarChar(50)")]
		public string Nazwa_czesci
		{
			get
			{
				return this._Nazwa_czesci;
			}
			set
			{
				if ((this._Nazwa_czesci != value))
				{
					this.OnNazwa_czesciChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_czesci = value;
					this.SendPropertyChanged("Nazwa_czesci");
					this.OnNazwa_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_czesci", DbType="VarChar(15)")]
		public string Nr_czesci
		{
			get
			{
				return this._Nr_czesci;
			}
			set
			{
				if ((this._Nr_czesci != value))
				{
					this.OnNr_czesciChanging(value);
					this.SendPropertyChanging();
					this._Nr_czesci = value;
					this.SendPropertyChanged("Nr_czesci");
					this.OnNr_czesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int")]
		public System.Nullable<int> id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this.Onid_dostawcyChanging(value);
					this.SendPropertyChanging();
					this._id_dostawcy = value;
					this.SendPropertyChanged("id_dostawcy");
					this.Onid_dostawcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_dostawy", DbType="Date")]
		public System.Nullable<System.DateTime> Data_dostawy
		{
			get
			{
				return this._Data_dostawy;
			}
			set
			{
				if ((this._Data_dostawy != value))
				{
					this.OnData_dostawyChanging(value);
					this.SendPropertyChanging();
					this._Data_dostawy = value;
					this.SendPropertyChanged("Data_dostawy");
					this.OnData_dostawyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_w_magazynie", DbType="NChar(10)")]
		public string Ilosc_w_magazynie
		{
			get
			{
				return this._Ilosc_w_magazynie;
			}
			set
			{
				if ((this._Ilosc_w_magazynie != value))
				{
					this.OnIlosc_w_magazynieChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_w_magazynie = value;
					this.SendPropertyChanged("Ilosc_w_magazynie");
					this.OnIlosc_w_magazynieChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.klienci")]
	public partial class klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_klient;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.Nullable<System.DateTime> _Data_pierwszej_wizyty;
		
		private string _Nazwa_firmy;
		
		private string _Nip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klientChanging(int value);
    partial void Onid_klientChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnData_pierwszej_wizytyChanging(System.Nullable<System.DateTime> value);
    partial void OnData_pierwszej_wizytyChanged();
    partial void OnNazwa_firmyChanging(string value);
    partial void OnNazwa_firmyChanged();
    partial void OnNipChanging(string value);
    partial void OnNipChanged();
    #endregion
		
		public klienci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klient", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_klient
		{
			get
			{
				return this._id_klient;
			}
			set
			{
				if ((this._id_klient != value))
				{
					this.Onid_klientChanging(value);
					this.SendPropertyChanging();
					this._id_klient = value;
					this.SendPropertyChanged("id_klient");
					this.Onid_klientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_pierwszej_wizyty", DbType="Date")]
		public System.Nullable<System.DateTime> Data_pierwszej_wizyty
		{
			get
			{
				return this._Data_pierwszej_wizyty;
			}
			set
			{
				if ((this._Data_pierwszej_wizyty != value))
				{
					this.OnData_pierwszej_wizytyChanging(value);
					this.SendPropertyChanging();
					this._Data_pierwszej_wizyty = value;
					this.SendPropertyChanged("Data_pierwszej_wizyty");
					this.OnData_pierwszej_wizytyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_firmy", DbType="Char(50)")]
		public string Nazwa_firmy
		{
			get
			{
				return this._Nazwa_firmy;
			}
			set
			{
				if ((this._Nazwa_firmy != value))
				{
					this.OnNazwa_firmyChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_firmy = value;
					this.SendPropertyChanged("Nazwa_firmy");
					this.OnNazwa_firmyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="NChar(10)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this.OnNipChanging(value);
					this.SendPropertyChanging();
					this._Nip = value;
					this.SendPropertyChanged("Nip");
					this.OnNipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SelectLoginResult
	{
		
		private string _Login;
		
		public SelectLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this._Login = value;
				}
			}
		}
	}
	
	public partial class SelectLogin2Result
	{
		
		private string _Login;
		
		public SelectLogin2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this._Login = value;
				}
			}
		}
	}
	
	public partial class czesci_wybórResult
	{
		
		private int _id_czesci;
		
		private string _Nazwa_czesci;
		
		private string _Nr_czesci;
		
		private System.Nullable<int> _id_dostawcy;
		
		private System.Nullable<System.DateTime> _Data_dostawy;
		
		private string _Ilosc_w_magazynie;
		
		public czesci_wybórResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", DbType="Int NOT NULL")]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this._id_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_czesci", DbType="VarChar(50)")]
		public string Nazwa_czesci
		{
			get
			{
				return this._Nazwa_czesci;
			}
			set
			{
				if ((this._Nazwa_czesci != value))
				{
					this._Nazwa_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_czesci", DbType="VarChar(15)")]
		public string Nr_czesci
		{
			get
			{
				return this._Nr_czesci;
			}
			set
			{
				if ((this._Nr_czesci != value))
				{
					this._Nr_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int")]
		public System.Nullable<int> id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_dostawy", DbType="Date")]
		public System.Nullable<System.DateTime> Data_dostawy
		{
			get
			{
				return this._Data_dostawy;
			}
			set
			{
				if ((this._Data_dostawy != value))
				{
					this._Data_dostawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_w_magazynie", DbType="NChar(10)")]
		public string Ilosc_w_magazynie
		{
			get
			{
				return this._Ilosc_w_magazynie;
			}
			set
			{
				if ((this._Ilosc_w_magazynie != value))
				{
					this._Ilosc_w_magazynie = value;
				}
			}
		}
	}
	
	public partial class select_czesciResult
	{
		
		private int _id_czesci;
		
		private string _Nazwa_czesci;
		
		private string _Nr_czesci;
		
		private System.Nullable<int> _id_dostawcy;
		
		private System.Nullable<System.DateTime> _Data_dostawy;
		
		private string _Ilosc_w_magazynie;
		
		public select_czesciResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", DbType="Int NOT NULL")]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this._id_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_czesci", DbType="VarChar(50)")]
		public string Nazwa_czesci
		{
			get
			{
				return this._Nazwa_czesci;
			}
			set
			{
				if ((this._Nazwa_czesci != value))
				{
					this._Nazwa_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_czesci", DbType="VarChar(15)")]
		public string Nr_czesci
		{
			get
			{
				return this._Nr_czesci;
			}
			set
			{
				if ((this._Nr_czesci != value))
				{
					this._Nr_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int")]
		public System.Nullable<int> id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_dostawy", DbType="Date")]
		public System.Nullable<System.DateTime> Data_dostawy
		{
			get
			{
				return this._Data_dostawy;
			}
			set
			{
				if ((this._Data_dostawy != value))
				{
					this._Data_dostawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_w_magazynie", DbType="NChar(10)")]
		public string Ilosc_w_magazynie
		{
			get
			{
				return this._Ilosc_w_magazynie;
			}
			set
			{
				if ((this._Ilosc_w_magazynie != value))
				{
					this._Ilosc_w_magazynie = value;
				}
			}
		}
	}
	
	public partial class select_dostawcyResult
	{
		
		private int _id_dostawcy;
		
		private string _Nazwa;
		
		private string _Kraj;
		
		public select_dostawcyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int NOT NULL")]
		public int id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(50)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this._Nazwa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kraj", DbType="VarChar(50)")]
		public string Kraj
		{
			get
			{
				return this._Kraj;
			}
			set
			{
				if ((this._Kraj != value))
				{
					this._Kraj = value;
				}
			}
		}
	}
	
	public partial class select_naprawyResult
	{
		
		private int _id_naprawy;
		
		private System.Nullable<int> _id_samochodu;
		
		private System.Nullable<System.DateTime> _Data_naprawy;
		
		private System.Nullable<int> _id_czesci;
		
		private System.Nullable<int> _id_mechanika;
		
		private System.Nullable<int> _id_koszt_naprawy;
		
		private System.Nullable<int> _id_raport_naprawy;
		
		public select_naprawyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_naprawy", DbType="Int NOT NULL")]
		public int id_naprawy
		{
			get
			{
				return this._id_naprawy;
			}
			set
			{
				if ((this._id_naprawy != value))
				{
					this._id_naprawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_samochodu", DbType="Int")]
		public System.Nullable<int> id_samochodu
		{
			get
			{
				return this._id_samochodu;
			}
			set
			{
				if ((this._id_samochodu != value))
				{
					this._id_samochodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_naprawy", DbType="Date")]
		public System.Nullable<System.DateTime> Data_naprawy
		{
			get
			{
				return this._Data_naprawy;
			}
			set
			{
				if ((this._Data_naprawy != value))
				{
					this._Data_naprawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", DbType="Int")]
		public System.Nullable<int> id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this._id_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mechanika", DbType="Int")]
		public System.Nullable<int> id_mechanika
		{
			get
			{
				return this._id_mechanika;
			}
			set
			{
				if ((this._id_mechanika != value))
				{
					this._id_mechanika = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_koszt_naprawy", DbType="Int")]
		public System.Nullable<int> id_koszt_naprawy
		{
			get
			{
				return this._id_koszt_naprawy;
			}
			set
			{
				if ((this._id_koszt_naprawy != value))
				{
					this._id_koszt_naprawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_raport_naprawy", DbType="Int")]
		public System.Nullable<int> id_raport_naprawy
		{
			get
			{
				return this._id_raport_naprawy;
			}
			set
			{
				if ((this._id_raport_naprawy != value))
				{
					this._id_raport_naprawy = value;
				}
			}
		}
	}
	
	public partial class select_samochodyResult
	{
		
		private int _id_samochodu;
		
		private string _Marka;
		
		private string _Model;
		
		private System.Nullable<System.DateTime> _DataSerwisu;
		
		private System.Nullable<int> _id_klienta;
		
		private string _nrVIN;
		
		public select_samochodyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_samochodu", DbType="Int NOT NULL")]
		public int id_samochodu
		{
			get
			{
				return this._id_samochodu;
			}
			set
			{
				if ((this._id_samochodu != value))
				{
					this._id_samochodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marka", DbType="VarChar(50)")]
		public string Marka
		{
			get
			{
				return this._Marka;
			}
			set
			{
				if ((this._Marka != value))
				{
					this._Marka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSerwisu", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataSerwisu
		{
			get
			{
				return this._DataSerwisu;
			}
			set
			{
				if ((this._DataSerwisu != value))
				{
					this._DataSerwisu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int")]
		public System.Nullable<int> id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this._id_klienta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrVIN", DbType="NChar(17)")]
		public string nrVIN
		{
			get
			{
				return this._nrVIN;
			}
			set
			{
				if ((this._nrVIN != value))
				{
					this._nrVIN = value;
				}
			}
		}
	}
	
	public partial class select_klienci_kontaktResult
	{
		
		private int _id_klienta;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Ulica;
		
		private string _Nr;
		
		private string _Kontakt_telefon;
		
		private string _Kontakt_email;
		
		public select_klienci_kontaktResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this._id_klienta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="Char(50)")]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this._Miasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="Char(50)")]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this._Kod_pocztowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="Char(50)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this._Ulica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr", DbType="Char(50)")]
		public string Nr
		{
			get
			{
				return this._Nr;
			}
			set
			{
				if ((this._Nr != value))
				{
					this._Nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_telefon", DbType="Char(50)")]
		public string Kontakt_telefon
		{
			get
			{
				return this._Kontakt_telefon;
			}
			set
			{
				if ((this._Kontakt_telefon != value))
				{
					this._Kontakt_telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_email", DbType="Char(50)")]
		public string Kontakt_email
		{
			get
			{
				return this._Kontakt_email;
			}
			set
			{
				if ((this._Kontakt_email != value))
				{
					this._Kontakt_email = value;
				}
			}
		}
	}
	
	public partial class select_dostawcy_kontaktResult
	{
		
		private int _id_dostawcy;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Ulica;
		
		private string _Nr;
		
		private string _Kontakt_telefon;
		
		private string _Kontakt_email;
		
		public select_dostawcy_kontaktResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int NOT NULL")]
		public int id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="Char(50)")]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this._Miasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="Char(50)")]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this._Kod_pocztowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="Char(50)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this._Ulica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr", DbType="Char(50)")]
		public string Nr
		{
			get
			{
				return this._Nr;
			}
			set
			{
				if ((this._Nr != value))
				{
					this._Nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_telefon", DbType="Char(9)")]
		public string Kontakt_telefon
		{
			get
			{
				return this._Kontakt_telefon;
			}
			set
			{
				if ((this._Kontakt_telefon != value))
				{
					this._Kontakt_telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_email", DbType="Char(50)")]
		public string Kontakt_email
		{
			get
			{
				return this._Kontakt_email;
			}
			set
			{
				if ((this._Kontakt_email != value))
				{
					this._Kontakt_email = value;
				}
			}
		}
	}
	
	public partial class select_klienciResult
	{
		
		private int _id_klienta;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.Nullable<System.DateTime> _Data_pierwszej_wizyty;
		
		private string _Nazwa_firmy;
		
		private string _Nip;
		
		public select_klienciResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this._id_klienta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this._Imie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this._Nazwisko = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_pierwszej_wizyty", DbType="Date")]
		public System.Nullable<System.DateTime> Data_pierwszej_wizyty
		{
			get
			{
				return this._Data_pierwszej_wizyty;
			}
			set
			{
				if ((this._Data_pierwszej_wizyty != value))
				{
					this._Data_pierwszej_wizyty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_firmy", DbType="Char(50)")]
		public string Nazwa_firmy
		{
			get
			{
				return this._Nazwa_firmy;
			}
			set
			{
				if ((this._Nazwa_firmy != value))
				{
					this._Nazwa_firmy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="NChar(10)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this._Nip = value;
				}
			}
		}
	}
	
	public partial class select_dostawcyResult1
	{
		
		private int _id_dostawcy;
		
		private string _Nazwa;
		
		private string _Kraj;
		
		public select_dostawcyResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int NOT NULL")]
		public int id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(50)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this._Nazwa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kraj", DbType="VarChar(50)")]
		public string Kraj
		{
			get
			{
				return this._Kraj;
			}
			set
			{
				if ((this._Kraj != value))
				{
					this._Kraj = value;
				}
			}
		}
	}
	
	public partial class select_czesciResult1
	{
		
		private int _id_czesci;
		
		private string _Nazwa_czesci;
		
		private string _Nr_czesci;
		
		private System.Nullable<int> _id_dostawcy;
		
		private System.Nullable<System.DateTime> _Data_dostawy;
		
		private string _Ilosc_w_magazynie;
		
		public select_czesciResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czesci", DbType="Int NOT NULL")]
		public int id_czesci
		{
			get
			{
				return this._id_czesci;
			}
			set
			{
				if ((this._id_czesci != value))
				{
					this._id_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_czesci", DbType="VarChar(50)")]
		public string Nazwa_czesci
		{
			get
			{
				return this._Nazwa_czesci;
			}
			set
			{
				if ((this._Nazwa_czesci != value))
				{
					this._Nazwa_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_czesci", DbType="VarChar(15)")]
		public string Nr_czesci
		{
			get
			{
				return this._Nr_czesci;
			}
			set
			{
				if ((this._Nr_czesci != value))
				{
					this._Nr_czesci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dostawcy", DbType="Int")]
		public System.Nullable<int> id_dostawcy
		{
			get
			{
				return this._id_dostawcy;
			}
			set
			{
				if ((this._id_dostawcy != value))
				{
					this._id_dostawcy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_dostawy", DbType="Date")]
		public System.Nullable<System.DateTime> Data_dostawy
		{
			get
			{
				return this._Data_dostawy;
			}
			set
			{
				if ((this._Data_dostawy != value))
				{
					this._Data_dostawy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_w_magazynie", DbType="NChar(10)")]
		public string Ilosc_w_magazynie
		{
			get
			{
				return this._Ilosc_w_magazynie;
			}
			set
			{
				if ((this._Ilosc_w_magazynie != value))
				{
					this._Ilosc_w_magazynie = value;
				}
			}
		}
	}
	
	public partial class klienci_select_id_where_miastoResult
	{
		
		private int _id_klienta;
		
		public klienci_select_id_where_miastoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this._id_klienta = value;
				}
			}
		}
	}
	
	public partial class klienci_select_id_where_miasto2Result
	{
		
		private int _id_klient;
		
		public klienci_select_id_where_miasto2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klient", DbType="Int NOT NULL")]
		public int id_klient
		{
			get
			{
				return this._id_klient;
			}
			set
			{
				if ((this._id_klient != value))
				{
					this._id_klient = value;
				}
			}
		}
	}
	
	public partial class widok_wstawianie_rezultatResult
	{
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.Nullable<System.DateTime> _Data_pierwszej_wizyty;
		
		private string _Nazwa_firmy;
		
		private string _Nip;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Ulica;
		
		private string _Nr;
		
		private string _Kontakt_telefon;
		
		private string _Kontakt_email;
		
		private string _Opis;
		
		public widok_wstawianie_rezultatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this._Imie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this._Nazwisko = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_pierwszej_wizyty", DbType="Date")]
		public System.Nullable<System.DateTime> Data_pierwszej_wizyty
		{
			get
			{
				return this._Data_pierwszej_wizyty;
			}
			set
			{
				if ((this._Data_pierwszej_wizyty != value))
				{
					this._Data_pierwszej_wizyty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_firmy", DbType="Char(50)")]
		public string Nazwa_firmy
		{
			get
			{
				return this._Nazwa_firmy;
			}
			set
			{
				if ((this._Nazwa_firmy != value))
				{
					this._Nazwa_firmy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="NChar(10)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this._Nip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="Char(50)")]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this._Miasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="Char(50)")]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this._Kod_pocztowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="Char(50)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this._Ulica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr", DbType="Char(50)")]
		public string Nr
		{
			get
			{
				return this._Nr;
			}
			set
			{
				if ((this._Nr != value))
				{
					this._Nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_telefon", DbType="Char(50)")]
		public string Kontakt_telefon
		{
			get
			{
				return this._Kontakt_telefon;
			}
			set
			{
				if ((this._Kontakt_telefon != value))
				{
					this._Kontakt_telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_email", DbType="Char(50)")]
		public string Kontakt_email
		{
			get
			{
				return this._Kontakt_email;
			}
			set
			{
				if ((this._Kontakt_email != value))
				{
					this._Kontakt_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NChar(100)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this._Opis = value;
				}
			}
		}
	}
	
	public partial class widok_wstawianie_rezultatResult1
	{
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.Nullable<System.DateTime> _Data_pierwszej_wizyty;
		
		private string _Nazwa_firmy;
		
		private string _Nip;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Ulica;
		
		private string _Nr;
		
		private string _Kontakt_telefon;
		
		private string _Kontakt_email;
		
		private string _Opis;
		
		public widok_wstawianie_rezultatResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this._Imie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this._Nazwisko = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_pierwszej_wizyty", DbType="Date")]
		public System.Nullable<System.DateTime> Data_pierwszej_wizyty
		{
			get
			{
				return this._Data_pierwszej_wizyty;
			}
			set
			{
				if ((this._Data_pierwszej_wizyty != value))
				{
					this._Data_pierwszej_wizyty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_firmy", DbType="Char(50)")]
		public string Nazwa_firmy
		{
			get
			{
				return this._Nazwa_firmy;
			}
			set
			{
				if ((this._Nazwa_firmy != value))
				{
					this._Nazwa_firmy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="NChar(10)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this._Nip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="Char(50)")]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this._Miasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="Char(50)")]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this._Kod_pocztowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="Char(50)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this._Ulica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr", DbType="Char(50)")]
		public string Nr
		{
			get
			{
				return this._Nr;
			}
			set
			{
				if ((this._Nr != value))
				{
					this._Nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_telefon", DbType="Char(50)")]
		public string Kontakt_telefon
		{
			get
			{
				return this._Kontakt_telefon;
			}
			set
			{
				if ((this._Kontakt_telefon != value))
				{
					this._Kontakt_telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt_email", DbType="Char(50)")]
		public string Kontakt_email
		{
			get
			{
				return this._Kontakt_email;
			}
			set
			{
				if ((this._Kontakt_email != value))
				{
					this._Kontakt_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NChar(100)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this._Opis = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
